### ISSUE TITLE
Create a repository with a list of public code projects

### ISSUE THREAD

**Issue by AlbaRoza** [publiccodenet/publiccode.net#121]
Detailed directory of public code codebases in use all around the world to avoid the parallel creation of very similar codebases.

The list would not only contain the names and the current users/replicators of them, but also what problem they solve.

**Comment by clausmullie** [comment]
Hi @AlbaRoza 

While this is a great idea, it is very hard to do in practice, especially for us. 

It is difficult because you need to meaningfully define public code (which is more specific than open source), and then define what information you will include about them. This is easy at first, but quickly becomes very complex. Typically it takes a lot of investment to make the first mapping. This mapping is near impossible to make complete (you always miss some codebases/projects, and/or some information about them), and this mapping quickly becomes out of date (information changes, and it's hard to monitor what needs to be updated.

A solution like [publiccode.yml](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/index.html) means that everyone is responsible to update their own information, on a small file in their repository, which can then be scraped by anyone to make a catalogue. You can search github for the filename [like this](https://github.com/search?p=4&q=filename%3Apubliccode.yml+path%3A%2F&type=Code)

Alternatively, the European Commission is making an [open source inventory for public organisations](https://joinup.ec.europa.eu/collection/sharing-and-reuse-it-solutions/news/pan-european-open-source-inventory), which is all open source, not only public code, but also only in Europe. There are also things such as [publiccode.directory](https://publiccode.directory/), the [IDB list](https://code.iadb.org/en) which is mainly focused on code for development, and another similar effort in Germany (@lscheske - can you remind me what this is called?).

I would propose closing this issue, as publiccode.yml is the solution recommended in the standard for public code, and other parties are already trying to do a centralised mapping.

**Comment by AlbaRoza** [comment]
> Hi @AlbaRoza
> 
> While this is a great idea, it is very hard to do in practice, especially for us. 
> 
> It is difficult because you need to meaningfully define public code (which is more specific than open source), and then define what information you will include about them. This is easy at first, but quickly becomes very complex. Typically it takes a lot of investment to make the first mapping. This mapping is near impossible to make complete (you always miss some codebases/projects, and/or some information about them), and this mapping quickly becomes out of date (information changes, and it's hard to monitor what needs to be updated.
> 
> A solution like [publiccode.yml](https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/index.html) means that everyone is responsible to update their own information, on a small file in their repository, which can then be scraped by anyone to make a catalogue. You can search github for the filename [like this](https://github.com/search?p=4&q=filename%3Apubliccode.yml+path%3A%2F&type=Code)
> 
> Alternatively, the European Commission is making an [open source inventory for public organisations](https://joinup.ec.europa.eu/collection/sharing-and-reuse-it-solutions/news/pan-european-open-source-inventory), which is all open source, not only public code, but also only in Europe. There are also things such as [publiccode.directory](https://publiccode.directory/), the [IDB list](https://code.iadb.org/en) which is mainly focused on code for development, and another similar effort in Germany (@lscheske - can you remind me what this is called?).
> 
> I would propose closing this issue, as publiccode.yml is the solution recommended in the standard for public code, and other parties are already trying to do a centralised mapping.

Thanks for your input @clausmullie , very interesting! The project I had envisioned was more like a collaborative one in which people would just upload their codebases in a markdown format, so sort of a basic list with links, basically.

**Comment by clausmullie** [comment]
> Thanks for your input @clausmullie , very interesting! The project I had envisioned was more like a collaborative one in which people would just upload their codebases in a markdown format, so sort of a basic list with links, basically.

Ok, in that case, I think publiccode.yml covers this quite well. So I'm going to close this issue for now.
